# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import fuota_pb2 as fuota__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in fuota_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FuotaServerServiceStub(object):
    """FUOTAServerService provides the fuota-server API methods.
    Note: this API considered experimental.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDeployment = channel.unary_unary(
                '/fuota.FuotaServerService/CreateDeployment',
                request_serializer=fuota__pb2.CreateDeploymentRequest.SerializeToString,
                response_deserializer=fuota__pb2.CreateDeploymentResponse.FromString,
                _registered_method=True)
        self.GetDeploymentStatus = channel.unary_unary(
                '/fuota.FuotaServerService/GetDeploymentStatus',
                request_serializer=fuota__pb2.GetDeploymentStatusRequest.SerializeToString,
                response_deserializer=fuota__pb2.GetDeploymentStatusResponse.FromString,
                _registered_method=True)
        self.GetDeploymentDeviceLogs = channel.unary_unary(
                '/fuota.FuotaServerService/GetDeploymentDeviceLogs',
                request_serializer=fuota__pb2.GetDeploymentDeviceLogsRequest.SerializeToString,
                response_deserializer=fuota__pb2.GetDeploymentDeviceLogsResponse.FromString,
                _registered_method=True)


class FuotaServerServiceServicer(object):
    """FUOTAServerService provides the fuota-server API methods.
    Note: this API considered experimental.
    """

    def CreateDeployment(self, request, context):
        """CreateDeployment creates the given FUOTA deployment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeploymentStatus(self, request, context):
        """GetDeploymentStatus returns the FUOTA deployment status given an ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeploymentDeviceLogs(self, request, context):
        """GetDeploymentDeviceLogs returns the FUOTA logs given a deployment ID and
        DevEUI.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FuotaServerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDeployment,
                    request_deserializer=fuota__pb2.CreateDeploymentRequest.FromString,
                    response_serializer=fuota__pb2.CreateDeploymentResponse.SerializeToString,
            ),
            'GetDeploymentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeploymentStatus,
                    request_deserializer=fuota__pb2.GetDeploymentStatusRequest.FromString,
                    response_serializer=fuota__pb2.GetDeploymentStatusResponse.SerializeToString,
            ),
            'GetDeploymentDeviceLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeploymentDeviceLogs,
                    request_deserializer=fuota__pb2.GetDeploymentDeviceLogsRequest.FromString,
                    response_serializer=fuota__pb2.GetDeploymentDeviceLogsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fuota.FuotaServerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fuota.FuotaServerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FuotaServerService(object):
    """FUOTAServerService provides the fuota-server API methods.
    Note: this API considered experimental.
    """

    @staticmethod
    def CreateDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fuota.FuotaServerService/CreateDeployment',
            fuota__pb2.CreateDeploymentRequest.SerializeToString,
            fuota__pb2.CreateDeploymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeploymentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fuota.FuotaServerService/GetDeploymentStatus',
            fuota__pb2.GetDeploymentStatusRequest.SerializeToString,
            fuota__pb2.GetDeploymentStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeploymentDeviceLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fuota.FuotaServerService/GetDeploymentDeviceLogs',
            fuota__pb2.GetDeploymentDeviceLogsRequest.SerializeToString,
            fuota__pb2.GetDeploymentDeviceLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
